- project:
    templates:
      - check-requirements
      - designate-devstack-jobs
      - openstack-cover-jobs-horizon
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - openstack-python36-jobs-horizon
      - openstack-python37-jobs-horizon
      - publish-openstack-docs-pti
    check:
      jobs:
        - horizon-openstack-tox-python3-django111
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            voting: false
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            voting: false
    gate:
      queue: designate
      jobs:
        - horizon-openstack-tox-python3-django111
